# Generated by Django 6.0.1 on 2026-02-01 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_guestsession_options_guestsession_session_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_units', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms')], default='lbs', max_length=3)),
                ('time_format', models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='12h', max_length=3)),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_push', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en-US', max_length=16)),
                ('public_profile', models.BooleanField(default=True)),
                ('default_rest_timer_seconds', models.PositiveIntegerField(default=90)),
                ('metric_rounding', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
