# Generated by Django 6.0.1 on 2026-02-01 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('weightlifting', 'Weightlifting'), ('powerlifting', 'Powerlifting'), ('gymnastics', 'Gymnastics'), ('monostructural', 'Monostructural'), ('accessory', 'Accessory'), ('mobility', 'Mobility'), ('other', 'Other')], default='other', max_length=20)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('medicine_ball', 'Medicine Ball'), ('box', 'Plyo Box'), ('rig', 'Pull-up Rig'), ('rings', 'Rings'), ('rope', 'Climbing Rope'), ('rower', 'Rower'), ('bike', 'Bike'), ('ski_erg', 'SkiErg'), ('assault_runner', 'Assault Runner'), ('jump_rope', 'Jump Rope'), ('sled', 'Sled'), ('sandbag', 'Sandbag'), ('pegboard', 'Pegboard'), ('other', 'Other')], default='bodyweight', max_length=20)),
                ('primary_muscle_group', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
