# Generated by Django 6.0.1 on 2026-02-04 00:00

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0002_alter_exercise_name_exercise_exercise_name_not_blank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('weightlifting', 'Weightlifting'), ('powerlifting', 'Powerlifting'), ('gymnastics', 'Gymnastics'), ('monostructural', 'Monostructural'), ('accessory', 'Accessory'), ('mobility', 'Mobility'), ('other', 'Other')], default='other', max_length=20)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('medicine_ball', 'Medicine Ball'), ('box', 'Plyo Box'), ('rig', 'Pull-up Rig'), ('rings', 'Rings'), ('rope', 'Climbing Rope'), ('rower', 'Rower'), ('bike', 'Bike'), ('ski_erg', 'SkiErg'), ('assault_runner', 'Assault Runner'), ('jump_rope', 'Jump Rope'), ('sled', 'Sled'), ('sandbag', 'Sandbag'), ('pegboard', 'Pegboard'), ('other', 'Other')], default='bodyweight', max_length=20)),
                ('primary_muscle_group', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wodtrackr.customexercise')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wodtrackr.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customexercise',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='custom_exercise_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='customexercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), 'created_by', name='custom_exercise_title_unique_ci'),
        ),
        migrations.AddIndex(
            model_name='customexercise',
            index=models.Index(fields=['title'], name='wodtrackr_customexercise_title_idx'),
        ),
        migrations.AddIndex(
            model_name='customexercise',
            index=models.Index(fields=['category'], name='wodtrackr_customexercise_category_idx'),
        ),
        migrations.AddIndex(
            model_name='customexercise',
            index=models.Index(fields=['equipment'], name='wodtrackr_customexercise_equipment_idx'),
        ),
        migrations.AddIndex(
            model_name='customexercise',
            index=models.Index(fields=['created_by'], name='wodtrackr_customexercise_created_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisenote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exercise__isnull', False), ('custom_exercise__isnull', True)), models.Q(('exercise__isnull', True), ('custom_exercise__isnull', False)), _connector='OR'), name='exercise_note_single_target'),
        ),
        migrations.AddConstraint(
            model_name='exercisenote',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='unique_note_per_user_exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercisenote',
            constraint=models.UniqueConstraint(fields=('user', 'custom_exercise'), name='unique_note_per_user_custom_exercise'),
        ),
        migrations.AddIndex(
            model_name='exercisenote',
            index=models.Index(fields=['user'], name='wodtrackr_exercisenote_user_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisenote',
            index=models.Index(fields=['exercise'], name='wodtrackr_exercisenote_exercise_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisenote',
            index=models.Index(fields=['custom_exercise'], name='wodtrackr_exercisenote_custom_exercise_idx'),
        ),
    ]
