# Generated by Django 6.0.1 on 2026-02-05 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0003_custom_exercise_and_exercise_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customexercise',
            new_name='wodtrackr_c_title_353e45_idx',
            old_name='wodtrackr_customexercise_title_idx',
        ),
        migrations.RenameIndex(
            model_name='customexercise',
            new_name='wodtrackr_c_categor_8489f8_idx',
            old_name='wodtrackr_customexercise_category_idx',
        ),
        migrations.RenameIndex(
            model_name='customexercise',
            new_name='wodtrackr_c_equipme_818cff_idx',
            old_name='wodtrackr_customexercise_equipment_idx',
        ),
        migrations.RenameIndex(
            model_name='customexercise',
            new_name='wodtrackr_c_created_af85ef_idx',
            old_name='wodtrackr_customexercise_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='exercisenote',
            new_name='wodtrackr_e_user_id_1211f7_idx',
            old_name='wodtrackr_exercisenote_user_idx',
        ),
        migrations.RenameIndex(
            model_name='exercisenote',
            new_name='wodtrackr_e_exercis_c7d292_idx',
            old_name='wodtrackr_exercisenote_exercise_idx',
        ),
        migrations.RenameIndex(
            model_name='exercisenote',
            new_name='wodtrackr_e_custom__e82f91_idx',
            old_name='wodtrackr_exercisenote_custom_exercise_idx',
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='wodtrackr_e_name_089142_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['category'], name='wodtrackr_e_categor_638bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['equipment'], name='wodtrackr_e_equipme_718a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_public'], name='wodtrackr_e_is_publ_d9fae7_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['created_by'], name='wodtrackr_e_created_33bd17_idx'),
        ),
    ]
