# Generated by Django 6.0.2 on 2026-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0004_rename_wodtrackr_customexercise_title_idx_wodtrackr_c_title_353e45_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customexercise',
            name='primary_muscle_group',
            field=models.CharField(blank=True, choices=[('back', 'Back'), ('cardio', 'Cardio'), ('chest', 'Chest'), ('core', 'Core'), ('full_body', 'Full Body'), ('glutes', 'Glutes'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle_group',
            field=models.CharField(blank=True, choices=[('back', 'Back'), ('cardio', 'Cardio'), ('chest', 'Chest'), ('core', 'Core'), ('full_body', 'Full Body'), ('glutes', 'Glutes'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('other', 'Other')], max_length=50),
        ),
    ]
