# Generated by Django 6.0.2 on 2026-03-03 18:30

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0005_alter_customexercise_primary_muscle_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customexercise',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='customexercise',
            name='custom_exercise_title_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='customexercise',
            name='custom_exercise_title_unique_ci',
        ),
        migrations.RemoveIndex(
            model_name='customexercise',
            name='wodtrackr_c_title_353e45_idx',
        ),
        migrations.RenameField(
            model_name='customexercise',
            old_name='title',
            new_name='name',
        ),
        migrations.AddIndex(
            model_name='customexercise',
            index=models.Index(fields=['name'], name='wodtrackr_c_name_43ea12_idx'),
        ),
        migrations.AddIndex(
            model_name='customexercise',
            index=models.Index(fields=['primary_muscle_group'], name='wodtrackr_c_primary_4e9b86_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['primary_muscle_group'], name='wodtrackr_e_primary_f24b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['created_at'], name='wodtrackr_e_created_f047cc_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['updated_at'], name='wodtrackr_e_updated_b22535_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['created_by', 'is_public'], name='wodtrackr_e_created_ea75a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='customexercise',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='custom_exercise_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='customexercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('created_by'), name='custom_exercise_name_unique_ci'),
        ),
    ]
