# Generated by Django 6.0.2 on 2026-05-03 14:57

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0006_alter_customexercise_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='wodtrackr.customexercise')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='wodtrackr.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wodtrackr.exerciseprogram')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['name'], name='wodtrackr_e_name_0d0dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['created_by'], name='wodtrackr_e_created_63e964_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['is_public'], name='wodtrackr_e_is_publ_fa36a1_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['created_at'], name='wodtrackr_e_created_d8c079_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['updated_at'], name='wodtrackr_e_updated_547d17_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['created_by', 'is_public'], name='wodtrackr_e_created_ad204e_idx'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogram',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='exercise_program_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('created_by'), name='exercise_program_name_unique_ci'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogramitem',
            index=models.Index(fields=['program'], name='wodtrackr_e_program_c4fd65_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogramitem',
            index=models.Index(fields=['exercise'], name='wodtrackr_e_exercis_7f372e_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogramitem',
            index=models.Index(fields=['custom_exercise'], name='wodtrackr_e_custom__9a209a_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogramitem',
            index=models.Index(fields=['position'], name='wodtrackr_e_positio_403204_idx'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogramitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exercise__isnull', False), ('custom_exercise__isnull', True)), models.Q(('exercise__isnull', True), ('custom_exercise__isnull', False)), _connector='OR'), name='exercise_program_item_single_target'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogramitem',
            constraint=models.UniqueConstraint(fields=('program', 'position'), name='exercise_program_item_position_unique'),
        ),
    ]
