# Generated by Django 6.0.2 on 2026-05-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0007_exerciseprogram_exerciseprogramitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogramitem',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseprogramitem',
            name='load',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exerciseprogramitem',
            name='reps',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exerciseprogramitem',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseprogramitem',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseprogramitem',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='exerciseprogramitem',
            index=models.Index(fields=['week'], name='wodtrackr_e_week_402421_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogramitem',
            index=models.Index(fields=['day'], name='wodtrackr_e_day_29bcc8_idx'),
        ),
    ]
