# Generated by Django 6.0.2 on 2026-05-07 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0008_exerciseprogramitem_day_exerciseprogramitem_load_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogram',
            name='category',
            field=models.CharField(choices=[('weightlifting', 'Weightlifting'), ('powerlifting', 'Powerlifting'), ('gymnastics', 'Gymnastics'), ('monostructural', 'Monostructural'), ('accessory', 'Accessory'), ('mobility', 'Mobility'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='equipment',
            field=models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('medicine_ball', 'Medicine Ball'), ('box', 'Plyo Box'), ('rig', 'Pull-up Rig'), ('rings', 'Rings'), ('rope', 'Climbing Rope'), ('rower', 'Rower'), ('bike', 'Bike'), ('ski_erg', 'SkiErg'), ('assault_runner', 'Assault Runner'), ('jump_rope', 'Jump Rope'), ('sled', 'Sled'), ('sandbag', 'Sandbag'), ('pegboard', 'Pegboard'), ('other', 'Other')], default='bodyweight', max_length=20),
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='primary_muscle_group',
            field=models.CharField(blank=True, choices=[('back', 'Back'), ('cardio', 'Cardio'), ('chest', 'Chest'), ('core', 'Core'), ('full_body', 'Full Body'), ('glutes', 'Glutes'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['category'], name='wodtrackr_e_categor_1ab3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['equipment'], name='wodtrackr_e_equipme_2abd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['primary_muscle_group'], name='wodtrackr_e_primary_79c922_idx'),
        ),
    ]
