# Generated by Django 6.0.2 on 2026-05-07 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0009_exerciseprogram_category_exerciseprogram_equipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogram',
            name='goal',
            field=models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance'), ('fat_loss', 'Fat Loss'), ('mobility', 'Mobility'), ('performance', 'Performance'), ('general_fitness', 'General Fitness'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['goal'], name='wodtrackr_e_goal_8e2d3b_idx'),
        ),
    ]
