# Generated by Django 6.0.2 on 2026-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0010_exerciseprogram_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogram',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['difficulty'], name='wodtrackr_e_difficu_8565f6_idx'),
        ),
    ]
