# Generated by Django 6.0.2 on 2026-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0011_exerciseprogram_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogram',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['duration_weeks'], name='wodtrackr_e_durati_bf7159_idx'),
        ),
    ]
