# Generated by Django 6.0.2 on 2026-05-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0011_exerciseprogram_difficulty'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exerciseprogram',
            new_name='wodtrackr_e_difficu_7029c9_idx',
            old_name='wodtrackr_e_difficu_8565f6_idx',
        ),
    ]
