# Generated by Django 6.0.2 on 2026-05-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0012_exerciseprogram_duration_weeks'),
        ('wodtrackr', '0012_rename_wodtrackr_e_difficu_8565f6_idx_wodtrackr_e_difficu_7029c9_idx'),
    ]

    operations = []