# Generated by Django 6.0.2 on 2026-05-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0013_merge_20260508_0322'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exerciseprogram',
            new_name='wodtrackr_e_duratio_d3aeef_idx',
            old_name='wodtrackr_e_durati_bf7159_idx',
        ),
    ]
