# Generated by Django 6.0.2 on 2026-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0014_rename_wodtrackr_e_durati_bf7159_idx_wodtrackr_e_duratio_d3aeef_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogram',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all levels', 'All Levels')], default='all_levels', max_length=20),
        ),
    ]
