# Generated by Django 6.0.2 on 2026-05-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0016_alter_exerciseprogram_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogram',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all levels', max_length=20),
        ),
    ]
