# Generated by Django 6.0.2 on 2026-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0017_alter_exerciseprogram_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('medicine_ball', 'Medicine Ball'), ('box', 'Plyo Box'), ('rig', 'Pull-up Rig'), ('rings', 'Rings'), ('rope', 'Climbing Rope'), ('rower', 'Rower'), ('bike', 'Bike'), ('ski_erg', 'SkiErg'), ('assault_runner', 'Assault Runner'), ('jump_rope', 'Jump Rope'), ('sled', 'Sled'), ('sandbag', 'Sandbag'), ('pegboard', 'Pegboard'), ('other', 'Other')], default='bodyweight', max_length=20)),
            ],
            options={
                'ordering': ['equipment'],
            },
        ),
        migrations.RemoveIndex(
            model_name='exerciseprogram',
            name='wodtrackr_e_equipme_2abd3b_idx',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='exercise_programs', to='wodtrackr.equipment'),
        ),
    ]
