# Generated by Django 6.0.2 on 2026-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0018_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment',
            field=models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('medicine_ball', 'Medicine Ball'), ('box', 'Plyo Box'), ('rig', 'Pull-up Rig'), ('rings', 'Rings'), ('rope', 'Climbing Rope'), ('rower', 'Rower'), ('bike', 'Bike'), ('ski_erg', 'SkiErg'), ('assault_runner', 'Assault Runner'), ('jump_rope', 'Jump Rope'), ('sled', 'Sled'), ('sandbag', 'Sandbag'), ('pegboard', 'Pegboard'), ('other', 'Other')], default='bodyweight', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='exerciseprogram',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all levels', 'All Levels')], default='all levels', max_length=20),
        ),
    ]
