# Generated by Django 6.0.2 on 2026-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0021_exerciseprogram_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogram',
            name='program_image',
            field=models.ImageField(blank=True, default='src/assets/Defaultbanner.jpg', null=True, upload_to='exercise_program_images/'),
        ),
    ]
