# Generated by Django 6.0.2 on 2026-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0024_alter_exerciseprogram_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogram',
            name='program_image',
            field=models.ImageField(default='exercise_program_images/Defaultbanner.jpg', upload_to='exercise_program_images/'),
        ),
    ]
