# Generated by Django 6.0.2 on 2026-07-10 13:49

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0027_backfill_program_image_existing_rows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customexercise',
            options={'ordering': ['title']},
        ),
        migrations.RemoveConstraint(
            model_name='customexercise',
            name='custom_exercise_name_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='customexercise',
            name='custom_exercise_name_unique_ci',
        ),
        migrations.RemoveIndex(
            model_name='customexercise',
            name='wodtrackr_c_name_43ea12_idx',
        ),
        migrations.RenameField(
            model_name='customexercise',
            old_name='name',
            new_name='title',
        ),
        migrations.AddIndex(
            model_name='customexercise',
            index=models.Index(fields=['title'], name='wodtrackr_c_title_353e45_idx'),
        ),
        migrations.AddConstraint(
            model_name='customexercise',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='custom_exercise_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='customexercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('created_by'), name='custom_exercise_title_unique_ci'),
        ),
    ]
