# Generated by Django 6.0.2 on 2026-07-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0028_alter_customexercise_options_and_more'),
    ]

    operations = [
    ]
