# Generated by Django 6.0.2 on 2026-07-10 18:27

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0029_backfill_program_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='exerciseprogram',
            options={'ordering': ['title']},
        ),
        migrations.RemoveConstraint(
            model_name='exercise',
            name='exercise_name_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='exercise',
            name='exercise_name_unique_ci',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseprogram',
            name='exercise_program_name_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseprogram',
            name='exercise_program_name_unique_ci',
        ),
        migrations.RemoveIndex(
            model_name='exercise',
            name='wodtrackr_e_name_089142_idx',
        ),
        migrations.RemoveIndex(
            model_name='exerciseprogram',
            name='wodtrackr_e_name_0d0dcb_idx',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='exerciseprogram',
            old_name='name',
            new_name='title',
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['title'], name='wodtrackr_e_title_b3f96c_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['title'], name='wodtrackr_e_title_f455fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='exercise_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='exercise_name_unique_ci'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogram',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='exercise_program_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('created_by'), name='exercise_program_name_unique_ci'),
        ),
    ]
