# Generated by Django 6.0.2 on 2026-07-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0030_alter_exercise_options_alter_exerciseprogram_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseprogram',
            name='program_image',
            field=models.ImageField(upload_to='exercise_program_images/'),
        ),
    ]
