# Generated by Django 6.0.2 on 2026-08-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0033_exercise_difficulty'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customexercise',
            name='wodtrackr_c_categor_8489f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='customexercise',
            name='wodtrackr_c_equipme_818cff_idx',
        ),
        migrations.RemoveIndex(
            model_name='customexercise',
            name='wodtrackr_c_created_af85ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='customexercise',
            name='wodtrackr_c_primary_4e9b86_idx',
        ),
        migrations.RemoveIndex(
            model_name='customexercise',
            name='wodtrackr_c_title_353e45_idx',
        ),
        migrations.RemoveConstraint(
            model_name='customexercise',
            name='custom_exercise_title_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='customexercise',
            name='custom_exercise_title_unique_ci',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='equipment',
        ),
        migrations.RemoveIndex(
            model_name='exercisenote',
            name='wodtrackr_e_user_id_1211f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercisenote',
            name='wodtrackr_e_exercis_c7d292_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercisenote',
            name='wodtrackr_e_custom__e82f91_idx',
        ),
        migrations.RemoveConstraint(
            model_name='exercisenote',
            name='exercise_note_single_target',
        ),
        migrations.RemoveConstraint(
            model_name='exercisenote',
            name='unique_note_per_user_exercise',
        ),
        migrations.RemoveConstraint(
            model_name='exercisenote',
            name='unique_note_per_user_custom_exercise',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseprogramitem',
            name='exercise_program_item_single_target',
        ),
        migrations.RemoveIndex(
            model_name='exerciseprogramitem',
            name='wodtrackr_e_custom__9a209a_idx',
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogramitem',
            constraint=models.CheckConstraint(condition=models.Q(('exercise__isnull', False)), name='exercise_program_item_single_target'),
        ),
        migrations.RemoveField(
            model_name='customexercise',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='equipment',
            field=models.CharField(blank=True, choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('medicine_ball', 'Medicine Ball'), ('box', 'Plyo Box'), ('rig', 'Pull-up Rig'), ('rings', 'Rings'), ('rope', 'Climbing Rope'), ('rower', 'Rower'), ('bike', 'Bike'), ('ski_erg', 'SkiErg'), ('assault_runner', 'Assault Runner'), ('jump_rope', 'Jump Rope'), ('sled', 'Sled'), ('sandbag', 'Sandbag'), ('pegboard', 'Pegboard'), ('other', 'Other')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='exerciseprogramitem',
            name='custom_exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseprogramitem',
            name='notes',
        ),
        migrations.DeleteModel(
            name='ExerciseNote',
        ),
        migrations.DeleteModel(
            name='CustomExercise',
        ),
    ]
