# Generated by Django 6.0.2 on 2026-09-01 11:52

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0034_remove_customexercise_wodtrackr_c_categor_8489f8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exerciseprogram',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='exercise',
            name='exercise_name_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='exercise',
            name='exercise_name_unique_ci',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseprogram',
            name='exercise_program_name_not_blank',
        ),
        migrations.RemoveConstraint(
            model_name='exerciseprogram',
            name='exercise_program_name_unique_ci',
        ),
        migrations.RemoveIndex(
            model_name='exercise',
            name='wodtrackr_e_primary_f24b0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercise',
            name='wodtrackr_e_title_b3f96c_idx',
        ),
        migrations.RemoveIndex(
            model_name='exerciseprogram',
            name='wodtrackr_e_categor_1ab3b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='exerciseprogram',
            name='wodtrackr_e_primary_79c922_idx',
        ),
        migrations.RemoveIndex(
            model_name='exerciseprogram',
            name='wodtrackr_e_goal_8e2d3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='exerciseprogram',
            name='wodtrackr_e_title_f455fc_idx',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='exerciseprogram',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='exercise',
            name='attribution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='dataset_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='dataset_id',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instruction_steps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='media_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_muscle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='exercises',
            field=models.ManyToManyField(to='wodtrackr.exercise', verbose_name='Exercises'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='wodtrackr_e_name_089142_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['dataset_id'], name='wodtrackr_e_dataset_3a7e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['body_part'], name='wodtrackr_e_body_pa_933dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_group'], name='wodtrackr_e_muscle__65216c_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['media_id'], name='wodtrackr_e_media_i_942e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['target_muscle'], name='wodtrackr_e_target__bac408_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseprogram',
            index=models.Index(fields=['name'], name='wodtrackr_e_name_0d0dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='exercise_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='exercise_name_unique_ci'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogram',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='exercise_program_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='exerciseprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('created_by'), name='exercise_program_name_unique_ci'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscle_group',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='primary_muscle_group',
        ),
    ]
