# Generated by Django 6.0.2 on 2026-09-01 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0035_alter_exercise_options_alter_exerciseprogram_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.AddField(
            model_name='exercise',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images/'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['images'], name='wodtrackr_e_images_2280ae_idx'),
        ),
    ]
