# Generated by Django 6.0.2 on 2026-09-01 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0036_remove_exercise_image_exercise_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exercise',
            name='wodtrackr_e_images_2280ae_idx',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='images',
            new_name='image',
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['image'], name='wodtrackr_e_image_256948_idx'),
        ),
    ]
