# Generated by Django 6.0.2 on 2026-09-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0037_remove_exercise_wodtrackr_e_images_2280ae_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/exercise_dataset/images/'),
        ),
    ]
