# Generated by Django 6.0.2 on 2026-09-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0039_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
