# Generated by Django 6.0.2 on 2026-09-01 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0040_alter_exercise_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exercise',
            name='wodtrackr_e_image_256948_idx',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_dataset/images/'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['image_url'], name='wodtrackr_e_image_u_dc1260_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['image_upload'], name='wodtrackr_e_image_u_be5141_idx'),
        ),
    ]
