# Generated by Django 6.0.2 on 2026-09-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0041_remove_exercise_wodtrackr_e_image_256948_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image_upload',
            field=models.ImageField(blank=True, default='exercise/_dataset/images/', null=True, upload_to='exercise_dataset/images/'),
        ),
    ]
