# Generated by Django 6.0.2 on 2026-09-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0042_alter_exercise_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True, default='exercise_dataset/images/exerciseLink.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_upload',
            field=models.ImageField(blank=True, default='exercise_dataset/images/exerciseLink.png', null=True, upload_to='exercise_dataset/images/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, default='exercise_dataset/images/exerciseLink.png', max_length=500, null=True),
        ),
    ]
