# Generated by Django 6.0.2 on 2026-09-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0043_alter_exercise_gif_url_alter_exercise_image_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif_upload',
            field=models.ImageField(blank=True, default='exercise_dataset/videos/1460-IZVHb27.gif', null=True, upload_to='exercise_dataset/videos/'),
        ),
    ]
