# Generated by Django 6.0.2 on 2026-09-14 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0044_exercise_gif_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['gif_url'], name='wodtrackr_e_gif_url_95fd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['gif_upload'], name='wodtrackr_e_gif_upl_07b967_idx'),
        ),
    ]
