# Generated by Django 6.0.2 on 2026-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodtrackr', '0045_exercise_wodtrackr_e_gif_url_95fd5a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogram',
            name='goals',
            field=models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance'), ('fat_loss', 'Fat Loss'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=20),
        ),
    ]
